# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_annee', models.PositiveSmallIntegerField(unique=True, verbose_name='Agê')),
                ('points', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='valeur')),
            ],
            options={
                'verbose_name_plural': 'ages',
                'db_table': 'age',
            },
        ),
        migrations.CreateModel(
            name='Bac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateField(verbose_name='date obtention')),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='moyenne')),
                ('type_bac_autre', models.CharField(blank=True, max_length=100, verbose_name='autre type de baccalauréat')),
            ],
            options={
                'verbose_name_plural': 'bacs',
                'db_table': 'bac',
            },
        ),
        migrations.CreateModel(
            name='BacType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=32, verbose_name='libelle')),
            ],
            options={
                'verbose_name_plural': 'bactypes',
                'db_table': 'bactype',
            },
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=50, unique=True, verbose_name='national identification code (CIN)')),
                ('cne', models.CharField(max_length=50, unique=True, verbose_name='national student code (CNE)')),
                ('nom', models.CharField(max_length=100, verbose_name='prénom')),
                ('prenom', models.CharField(max_length=100, verbose_name='nom')),
                ('nationalite', models.CharField(max_length=100, verbose_name='nationality')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='birth country')),
                ('date_nass', models.DateField(verbose_name='birth date')),
                ('preselection_note', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='semester 1 mark')),
                ('age_note', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='semester 1 mark')),
                ('concours_note', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='semester 1 mark')),
                ('moyenne_systeme_note', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='semester 1 mark')),
                ('validation_diplome_note', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='semester 1 mark')),
            ],
            options={
                'verbose_name_plural': 'candidats',
                'db_table': 'candidat',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='email')),
                ('portable_phone', models.CharField(max_length=20, unique=True, verbose_name='telephone portable')),
                ('fixe_phone', models.CharField(blank=True, max_length=20, verbose_name='telephone fixe')),
                ('adresse', models.CharField(max_length=255, verbose_name='adresse de residence')),
                ('ville', models.CharField(max_length=100, verbose_name='ville de residence')),
                ('pays', models.CharField(max_length=100, verbose_name='pays de residence')),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscription.Candidat', verbose_name='Candidat')),
            ],
            options={
                'verbose_name_plural': 'contacts',
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1_note', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='semester 1 mark')),
                ('s1_an', models.PositiveSmallIntegerField(verbose_name='semester 1 year')),
                ('s2_note', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='semester 2 mark')),
                ('s2_an', models.PositiveSmallIntegerField(verbose_name='semester 2 year')),
                ('s3_note', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='semester 3 mark')),
                ('s3_an', models.PositiveSmallIntegerField(verbose_name='semester 3 year')),
                ('s4_note', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='semester 4 mark')),
                ('s4_an', models.PositiveSmallIntegerField(verbose_name='semester 4 year')),
                ('date_obtention', models.DateField(verbose_name='date obtention')),
                ('type_diplome_autre', models.CharField(blank=True, max_length=100, verbose_name='autre type de diplome bac +2')),
                ('moyenne_1_an', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='semester 1 mark')),
                ('moyenne_2_an', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='semester 1 mark')),
                ('moyenneDiplome', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='semester 1 mark')),
            ],
            options={
                'verbose_name_plural': 'diplomes',
                'db_table': 'diplome',
            },
        ),
        migrations.CreateModel(
            name='DiplomeAnnee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_annee', models.PositiveSmallIntegerField(unique=True, verbose_name='max age')),
                ('points', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='value')),
            ],
            options={
                'verbose_name_plural': 'diplome_annees',
                'db_table': 'diplome_annee',
            },
        ),
        migrations.CreateModel(
            name='DiplomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=32, verbose_name='libelle')),
            ],
            options={
                'verbose_name_plural': 'diplometypes',
                'db_table': 'diplometype',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=32, verbose_name='libelle')),
                ('responsable', models.CharField(max_length=32, verbose_name='responsable')),
                ('diplometype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.DiplomeType')),
            ],
            options={
                'verbose_name_plural': 'filieres',
                'db_table': 'filiere',
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=32, verbose_name='libelle')),
                ('valeur', models.CharField(max_length=10, verbose_name='interval')),
            ],
            options={
                'verbose_name_plural': 'mentions',
                'db_table': 'mention',
            },
        ),
        migrations.CreateModel(
            name='OptionFiliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='option filiere')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Filiere')),
            ],
            options={
                'verbose_name_plural': 'optionfiliere',
                'db_table': 'optionfilieres',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialiteLP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=32, verbose_name='libelle')),
                ('responsable', models.CharField(max_length=32, verbose_name='responsable')),
            ],
            options={
                'verbose_name_plural': 'specialitelp',
                'db_table': 'specialitelp',
            },
        ),
        migrations.CreateModel(
            name='SpecialiteOptionFiliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionFiliere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.OptionFiliere', verbose_name='optionfiliere')),
                ('specialitelp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.SpecialiteLP', verbose_name='filierelp')),
            ],
            options={
                'verbose_name_plural': 'specialite_OPFs',
                'db_table': 'specialite_OPF',
            },
        ),
        migrations.AddField(
            model_name='diplome',
            name='diplometype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.DiplomeType'),
        ),
        migrations.AddField(
            model_name='diplome',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Filiere'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='diplome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscription.Diplome', verbose_name='diplome'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='diplomebac',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscription.Bac', verbose_name='degree specialty'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='specialitelp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.SpecialiteLP', verbose_name='specialitelp'),
        ),
        migrations.AddField(
            model_name='bac',
            name='mention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Mention'),
        ),
        migrations.AddField(
            model_name='bac',
            name='typebac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.BacType'),
        ),
    ]
