# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='diplome',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='diplomebac',
        ),
        migrations.AddField(
            model_name='bac',
            name='candidat',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='inscription.Candidat', verbose_name='candidatBac'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diplome',
            name='candidat',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='inscription.Candidat', verbose_name='candidatdiplome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidat',
            name='specialitelp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.SpecialiteLP', verbose_name='Specialité LP'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='candidat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscription.Candidat', verbose_name='Candidatinfo'),
        ),
    ]
