# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_auto_20170320_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='moyenne_systeme_note',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='specialitelp',
        ),
        migrations.AddField(
            model_name='diplome',
            name='specialitelp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inscription.SpecialiteLP', verbose_name='Specialité LP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidat',
            name='age_note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Note Âge'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='cin',
            field=models.CharField(max_length=50, unique=True, verbose_name='(CIN)'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='cne',
            field=models.CharField(max_length=50, unique=True, verbose_name='(CNE)'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='concours_note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Note concours'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_nass',
            field=models.DateField(verbose_name='date naissance'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='lieu_naissance',
            field=models.CharField(max_length=100, verbose_name='pays de nassaince'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='nationalite',
            field=models.CharField(max_length=100, verbose_name='nationalité'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='preselection_note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Note Pre-selection'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='validation_diplome_note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Validation diplome'),
        ),
    ]
