# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_auto_20170403_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_nass',
            field=models.DateField(verbose_name='Date naissance'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='lieu_naissance',
            field=models.CharField(max_length=100, verbose_name='Pays de nassaince'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='adresse',
            field=models.CharField(max_length=255, verbose_name='adresse de résidence'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=80, unique=True, verbose_name='Courriel'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='fixe_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telephone fixe'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='pays',
            field=models.CharField(max_length=100, verbose_name='pays de résidence'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='portable_phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telephone portable'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='ville',
            field=models.CharField(max_length=100, verbose_name='Ville de résidence'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='s1_an',
            field=models.CharField(max_length=10, verbose_name='(Année S1)'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='s1_note',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Note S1'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='s2_an',
            field=models.CharField(max_length=10, verbose_name='(Année S2)'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='s2_note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Note S2'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='s3_an',
            field=models.CharField(max_length=10, verbose_name='(Année S3)'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='s3_note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Note S3'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='s4_an',
            field=models.CharField(max_length=10, verbose_name='(Année S4)'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='s4_note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Note S4'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
