# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_auto_20170404_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bac',
            old_name='date_obtention',
            new_name='date_obtention_bac',
        ),
        migrations.RenameField(
            model_name='diplome',
            old_name='date_obtention',
            new_name='date_obtention_dip',
        ),
    ]
