# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_auto_20170404_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='valeur',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valeur'),
        ),
    ]
