# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 00:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0009_candidat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
